# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Devops Champion
description: Devops Champion - Beginning with Incident Response. Your systems are down! Customers are calling. Every moment counts. What do you do?
github_username: jasonhand
# you can comment the below line out if your repo name is not different than your baseurl
# github_repo: "fastpages"

# OPTIONAL: override baseurl and url if using a custom domain
url: "http://devopschampion.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. "/blog".  WARNING: if you are not using a custom domain, the baseurl *must* be set to your repo name.

# Email and twitter are optional:
email: 
twitter_username: "jasonhand"

# Set this to true to get LaTeX math equation support
use_math: false

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: false

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to display tags on each post
show_tags: false

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-159073323-1

# Added by Jason: Enabling Excerpts on the Home Page
show_excerpts: false

exclude:
  - CONTRIBUTING.md
  - DEVELOPMENT.md
  - settings.ini
  - docker-compose.yml
  - action.yml
  - README_TEMPLATE.md
  - Makefile

# Everything below here should be left alone. Modifications may break fastpages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
